from time import sleep 
print ('{:=^40}'.format(' SAQUE SEU DINHEIRO '))
sleep(1)
print ('Passos: ')
sleep(1)
print ('1° Se arrume para sair de casa')
sleep(1)
print ('2° Saia de casa e caminhe até o seu banco de preferência')
sleep(1)
print ('3° Entre no banco e encontre um caixa eletronico')
sleep(1)
print ('4° Coloque o seu cartão e siga os passos indicados dentro do caixa eletronico')
sleep(1)
print ('5° Selecione a opção para sacar o dinheiro, escolha o valor da sua preferencia e saque!')
sleep(1)
print ('{:=^40}'.format(' FIM '))